name: Tests
on: [push, pull_request]

jobs:
  Windows:
    name: windows-${{ matrix.os-version }}-${{ matrix.build-config }}-${{ matrix.build-arch }}${{ matrix.build-tool }}
    runs-on: windows-${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        os-version: [2022]
        build-config: [debug, release, relwithdebinfo]
        build-arch: [Win32, x64]
        build-tool: ["", "-T ClangCL"]
        exclude:
        - build-arch: Win32
          build-tool: "-T ClangCL"

    steps:
    - name: Versions
      shell: bash
      run: |
        cmake --version
        git --version

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -A${{ matrix.build-arch }} ${{ matrix.build-tool }} -DCMAKE_BUILD_TYPE=${{ matrix.build-config }} -Dcage_use_steam_sockets=OFF ..

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config ${{ matrix.build-config }}

    - name: Assets
      run: |
        cd build/result/${{ matrix.build-config }}
        ./cage-asset-database


  Ubuntu:
    name: ubuntu-${{ matrix.os-version }}-${{ matrix.build-config }}-${{ matrix.compiler.cc }}
    runs-on: ubuntu-${{ matrix.os-version }}.04
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    strategy:
      fail-fast: false
      matrix:
        os-version: [24]
        build-config: [debug, release]
        compiler:
        - {
            cc: gcc-14,
            cxx: g++-14,
            install: gcc-14 g++-14
          }
        - {
            cc: clang-18,
            cxx: clang++-18,
            install: clang-18
          }

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libwayland-dev libxkbcommon-dev libpulse-dev libasound2-dev nasm libssl-dev ${{ matrix.compiler.install }}

    - name: Versions
      run: |
        cmake --version
        git --version
        ${{ matrix.compiler.cc }} --version
        ${{ matrix.compiler.cxx }} --version

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-config }} -Dcage_use_steam_sockets=0 ..

    - name: Build
      run: |
        cd build
        cmake --build . -- -j$(( `nproc` + 1 ))

    - name: Assets
      run: |
        cd build/result/${{ matrix.build-config }}
        ./cage-asset-database
